"""add memory_entries table with pgvector

Revision ID: eaeb471056ff
Revises: 9ee85e6b3d94
Create Date: 2026-08-09 02:44:27.863557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaeb471056ff'
down_revision: Union[str, Sequence[str], None] = '9ee85e6b3d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
