"""initial migration

Revision ID: f91cf7b2ef5e
Revises: 27a6992282f6
Create Date: 2026-08-22 18:23:17.456332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91cf7b2ef5e'
down_revision: Union[str, Sequence[str], None] = '27a6992282f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE session_status ADD VALUE IF NOT EXISTS 'AWAITING_INPUT'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
